run:
  timeout: 1m

output:
  show-stats: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - /root/sdk
    - /root/go
    - data
    - test
#  fix: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
#    - cyclop
    - decorder
#    - depguard
    - dogsled
#    - dupl
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
#    - exhaustruct
    - exportloopref
    - fatcontext
    - forbidigo
    - forcetypeassert
#    - funlen
#    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
#    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
#    - gocognit
    - goconst
    - gocritic
#    - gocyclo
#    - godot
    - godox
#    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
#    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
#    - interfacebloat
    - intrange
#    - ireturn
#    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - stylecheck
    - tagalign
#    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
#    - wrapcheck
    - wsl
    - zerologlint


linters-settings:
  unused:
    # Mark all struct fields that have been written to as used.
    # Default: true
    field-writes-are-uses: false
  exhaustive:
    # Program elements to check for exhaustiveness.
    # Default: [ switch ]
    check:
      - switch
      - map
    default-signifies-exhaustive: true
  gofumpt:
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: true
  nlreturn:
    # Size of the block (including return statement that is still "OK")
    # so no return split required.
    # Default: 1
    block-size: 2
  varnamelen:
    ignore-decls:
      - c *gin.Context
      - i int